
/*
 * Structures for model: d_hdl
 *
 * Automatically generated by cmpp preprocessor
 *
 * !!! DO NOT EDIT !!!
 *
 */


#include "ngspice/ngspice.h"
#include <stdio.h>
#include "ngspice/devdefs.h"
#include "ngspice/ifsim.h"
#include "ngspice/mifdefs.h"
#include "ngspice/mifproto.h"
#include "ngspice/mifparse.h"


static IFparm MIFmPTable[] = {
    IOP("pipe_name", 0, IF_STRING, "AF_UNIX Pipe to HDL simulator"),
    IOP("tohdl_load", 1, IF_REAL, "toHDL pin loading capacitance (F)"),
    IOP("sampclk_load", 2, IF_REAL, "Sampling Clock pin loading capacitance (F)"),
    IOP("rise_delay", 3, IF_REAL, "to NGSPICE rise delay"),
    IOP("fall_delay", 4, IF_REAL, "to NGSPICE fall delay"),
    IOP("debug", 5, IF_FLAG, "Print Debug Data"),
    IOP("ic", 6, IF_INTEGER, "Initial Conditions"),
};


static IFparm MIFpTable[] = {
    OP("commchannel", 7, IF_STRING, "local static data"),
    OP("direction", 8, IF_INTEGER, "toggle direction"),
};


static Mif_Port_Type_t MIFportEnum0[] = {
	MIF_DIGITAL,
};


static char *MIFportStr0[] = {
	"d",
};


static Mif_Port_Type_t MIFportEnum1[] = {
	MIF_DIGITAL,
};


static char *MIFportStr1[] = {
	"d",
};


static Mif_Port_Type_t MIFportEnum2[] = {
	MIF_DIGITAL,
};


static char *MIFportStr2[] = {
	"d",
};


static Mif_Conn_Info_t MIFconnTable[] = {
  {
    "tohdl",
    "To HDL Bus",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum0,
    MIFportStr0,
    MIF_TRUE,
    MIF_FALSE,
    0,
    MIF_TRUE,
    255,
    MIF_TRUE,
  },
  {
    "tongspice",
    "To NGSPICE Bus",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum1,
    MIFportStr1,
    MIF_TRUE,
    MIF_FALSE,
    0,
    MIF_TRUE,
    255,
    MIF_TRUE,
  },
  {
    "sampclk",
    "Sampling Clock",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum2,
    MIFportStr2,
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
};


static Mif_Param_Info_t MIFparamTable[] = {
  {
    "pipe_name",
    "AF_UNIX Pipe to HDL simulator",
    MIF_STRING,
    MIF_TRUE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, "simulator_pipe"},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
  },
  {
    "tohdl_load",
    "toHDL pin loading capacitance (F)",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
  },
  {
    "sampclk_load",
    "Sampling Clock pin loading capacitance (F)",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
  },
  {
    "rise_delay",
    "to NGSPICE rise delay",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-09, {0.0, 0.0}, NULL},
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "fall_delay",
    "to NGSPICE fall delay",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-09, {0.0, 0.0}, NULL},
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "debug",
    "Print Debug Data",
    MIF_BOOLEAN,
    MIF_TRUE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "ic",
    "Initial Conditions",
    MIF_INTEGER,
    MIF_TRUE,
    {MIF_FALSE, -1, 0.0, {0.0, 0.0}, NULL},
    MIF_TRUE,
    {MIF_FALSE, -1, 0.0, {0.0, 0.0}, NULL},
    MIF_TRUE,
    {MIF_FALSE, 1, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
};


static Mif_Inst_Var_Info_t MIFinst_varTable[] = {
  {
    "commchannel",
    "local static data",
    MIF_STRING,
    MIF_FALSE,
  },
  {
    "direction",
    "toggle direction",
    MIF_INTEGER,
    MIF_FALSE,
  },
};


extern void cm_d_hdl(Mif_Private_t *);

static int val_terms             = 0;
static int val_numNames          = 0;
static int val_numInstanceParms  = 2;
static int val_numModelParms     = 7;
static int val_sizeofMIFinstance = sizeof(MIFinstance);
static int val_sizeofMIFmodel    = sizeof(MIFmodel);

SPICEdev cm_d_hdl_info = {
    { "d_hdl",
      "digital Xspice to HDL bridge",
      &val_terms,
      &val_numNames,
      NULL,
      &val_numInstanceParms,
      MIFpTable,
      &val_numModelParms,
      MIFmPTable,
      cm_d_hdl,
      3,
      MIFconnTable,
      7,
      MIFparamTable,
      2,
      MIFinst_varTable,
      0,         /* flags */
    },
NULL,          
MIFmParam,     
MIFload,       
MIFsetup,      
MIFunsetup,    
NULL,          
NULL,          
MIFtrunc,      
NULL,          
MIFload,       
NULL,          
MIFdestroy,    
MIFmDelete,    
MIFdelete,     
NULL,          
MIFask,        
MIFmAsk,       
NULL,          
MIFconvTest,   
NULL,          
NULL,          
NULL,          
NULL,          
NULL,          
NULL,          
NULL,          
NULL,          
NULL,          
#ifdef CIDER   
NULL,          
NULL,          
#endif         
&val_sizeofMIFinstance,
&val_sizeofMIFmodel,

};

