/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "../verilog/rtl/ACMP_HVL.v:5" *)
module ACMP_HVL(clk, INP, INN, Q);
  (* src = "../verilog/rtl/ACMP_HVL.v:8" *)
  input INN;
  (* src = "../verilog/rtl/ACMP_HVL.v:7" *)
  input INP;
  (* src = "../verilog/rtl/ACMP_HVL.v:9" *)
  output Q;
  (* src = "../verilog/rtl/ACMP_HVL.v:12" *)
  wire Q1;
  (* src = "../verilog/rtl/ACMP_HVL.v:12" *)
  wire Q1b;
  (* src = "../verilog/rtl/ACMP_HVL.v:13" *)
  wire Q2;
  (* src = "../verilog/rtl/ACMP_HVL.v:13" *)
  wire Q2b;
  (* src = "../verilog/rtl/ACMP_HVL.v:14" *)
  wire Qb;
  (* src = "../verilog/rtl/ACMP_HVL.v:6" *)
  input clk;
  (* src = "../verilog/rtl/ACMP_HVL.v:11" *)
  wire clkb;
  (* src = "../verilog/rtl/ACMP_HVL.v:35|../verilog/rtl/ACMP_HVL.v:83" *)
  wire \x1.Q0 ;
  (* src = "../verilog/rtl/ACMP_HVL.v:35|../verilog/rtl/ACMP_HVL.v:83" *)
  wire \x1.Q0b ;
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:16" *)
  sky130_fd_sc_hvl__inv_1 x0 (
    .A(clk),
    .Y(clkb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:35|../verilog/rtl/ACMP_HVL.v:85" *)
  sky130_fd_sc_hvl__nand3_1 \x1.x1  (
    .A(clk),
    .B(INP),
    .C(\x1.Q0 ),
    .Y(\x1.Q0b )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:35|../verilog/rtl/ACMP_HVL.v:91" *)
  sky130_fd_sc_hvl__nand3_1 \x1.x2  (
    .A(clk),
    .B(INN),
    .C(\x1.Q0b ),
    .Y(\x1.Q0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:35|../verilog/rtl/ACMP_HVL.v:98" *)
  sky130_fd_sc_hvl__inv_4 \x1.x3  (
    .A(\x1.Q0 ),
    .Y(Q1b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:35|../verilog/rtl/ACMP_HVL.v:103" *)
  sky130_fd_sc_hvl__inv_4 \x1.x4  (
    .A(\x1.Q0b ),
    .Y(Q1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:43|../verilog/rtl/ACMP_HVL.v:61" *)
  sky130_fd_sc_hvl__nor3_1 \x2.x1  (
    .A(clkb),
    .B(INP),
    .C(Q2),
    .Y(Q2b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:43|../verilog/rtl/ACMP_HVL.v:67" *)
  sky130_fd_sc_hvl__nor3_1 \x2.x2  (
    .A(clkb),
    .B(INN),
    .C(Q2b),
    .Y(Q2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:21" *)
  sky130_fd_sc_hvl__nor3_1 x5 (
    .A(Q1b),
    .B(Q2b),
    .C(Qb),
    .Y(Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:28" *)
  sky130_fd_sc_hvl__nor3_1 x6 (
    .A(Q1),
    .B(Q2),
    .C(Q),
    .Y(Qb)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../verilog/rtl/ACMP_HVL.v:76" *)
module latch_nand3(CLK, VP, VN, Q, Qb);
  (* src = "../verilog/rtl/ACMP_HVL.v:77" *)
  input CLK;
  (* src = "../verilog/rtl/ACMP_HVL.v:80" *)
  output Q;
  (* src = "../verilog/rtl/ACMP_HVL.v:83" *)
  wire Q0;
  (* src = "../verilog/rtl/ACMP_HVL.v:83" *)
  wire Q0b;
  (* src = "../verilog/rtl/ACMP_HVL.v:81" *)
  output Qb;
  (* src = "../verilog/rtl/ACMP_HVL.v:79" *)
  input VN;
  (* src = "../verilog/rtl/ACMP_HVL.v:78" *)
  input VP;
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:85" *)
  sky130_fd_sc_hvl__nand3_1 x1 (
    .A(CLK),
    .B(VP),
    .C(Q0),
    .Y(Q0b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:91" *)
  sky130_fd_sc_hvl__nand3_1 x2 (
    .A(CLK),
    .B(VN),
    .C(Q0b),
    .Y(Q0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:98" *)
  sky130_fd_sc_hvl__inv_4 x3 (
    .A(Q0),
    .Y(Qb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:103" *)
  sky130_fd_sc_hvl__inv_4 x4 (
    .A(Q0b),
    .Y(Q)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../verilog/rtl/ACMP_HVL.v:53" *)
module latch_nor3(CLK, VP, VN, Q, Qb);
  (* src = "../verilog/rtl/ACMP_HVL.v:54" *)
  input CLK;
  (* src = "../verilog/rtl/ACMP_HVL.v:57" *)
  output Q;
  (* src = "../verilog/rtl/ACMP_HVL.v:58" *)
  output Qb;
  (* src = "../verilog/rtl/ACMP_HVL.v:56" *)
  input VN;
  (* src = "../verilog/rtl/ACMP_HVL.v:55" *)
  input VP;
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:61" *)
  sky130_fd_sc_hvl__nor3_1 x1 (
    .A(CLK),
    .B(VP),
    .C(Q),
    .Y(Qb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../verilog/rtl/ACMP_HVL.v:67" *)
  sky130_fd_sc_hvl__nor3_1 x2 (
    .A(CLK),
    .B(VN),
    .C(Qb),
    .Y(Q)
  );
endmodule
