/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "../ACMP.v:1" *)
module ACMP(clk, INP, INN, VDD, VSS, Q);
  (* src = "../ACMP.v:4" *)
  input INN;
  (* src = "../ACMP.v:3" *)
  input INP;
  (* src = "../ACMP.v:7" *)
  output Q;
  (* src = "../ACMP.v:5" *)
  input VDD;
  (* src = "../ACMP.v:6" *)
  input VSS;
  (* src = "../ACMP.v:2" *)
  input clk;
  (* src = "../ACMP.v:11" *)
  wire clkb;
  (* src = "../ACMP.v:12" *)
  wire net1;
  (* src = "../ACMP.v:12" *)
  wire net2;
  (* src = "../ACMP.v:12" *)
  wire net3;
  (* src = "../ACMP.v:12" *)
  wire net4;
  (* src = "../ACMP.v:12" *)
  wire net5;
  (* src = "../ACMP.v:12" *)
  wire net6;
  (* src = "../ACMP.v:12" *)
  wire net7;
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:27" *)
  sky130_fd_sc_hd__nor3_1 x10 (
    .A(net5),
    .B(net1),
    .C(net7),
    .Y(Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:28" *)
  sky130_fd_sc_hd__nor3_1 x11 (
    .A(Q),
    .B(net6),
    .C(net2),
    .Y(net7)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:20" *)
  sky130_fd_sc_hd__inv_1 x15 (
    .A(clk),
    .Y(clkb)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:23" *)
  sky130_fd_sc_hd__inv_1 x2 (
    .A(net3),
    .Y(net6)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:24" *)
  sky130_fd_sc_hd__inv_1 x3 (
    .A(net4),
    .Y(net5)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:25" *)
  sky130_fd_sc_hd__o221ai_1 x6 (
    .A1(INP),
    .A2(INP),
    .B1(clk),
    .B2(VSS),
    .C1(net4),
    .Y(net3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:21" *)
  sky130_fd_sc_hd__a221oi_1 x7 (
    .A1(INP),
    .A2(INP),
    .B1(clkb),
    .B2(VDD),
    .C1(net2),
    .Y(net1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:22" *)
  sky130_fd_sc_hd__a221oi_1 x8 (
    .A1(INN),
    .A2(INN),
    .B1(clkb),
    .B2(VDD),
    .C1(net1),
    .Y(net2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../ACMP.v:26" *)
  sky130_fd_sc_hd__o221ai_1 x9 (
    .A1(INN),
    .A2(INN),
    .B1(clk),
    .B2(VSS),
    .C1(net3),
    .Y(net4)
  );
endmodule
