/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

module SAR(clk, rst, start, cmp, out, outn, done, clkn, VGND, VNB, VPB, VPWR);
  input  VPWR;
  input  VGND;
  input  VPB ;
  input  VNB ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  input clk;
  output clkn;
  input cmp;
  output done;
  wire \next[0] ;
  wire \next[1] ;
  wire \next[2] ;
  wire \next[3] ;
  wire \next[4] ;
  wire \next[5] ;
  wire \next[6] ;
  output [7:0] out;
  output [7:0] outn;
  input rst;
  wire \shift[0] ;
  input start;
  wire \state[0] ;
  wire \state[2] ;
  sky130_fd_sc_hd__inv_2 _085_ (
    .A(rst),
    .Y(_021_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _086_ (
    .A(\next[0] ),
    .B_N(\shift[0] ),
    .Y(_052_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _087_ (
    .A(\next[2] ),
    .B(\next[1] ),
    .Y(_053_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _088_ (
    .A(\next[6] ),
    .B(\next[5] ),
    .Y(_054_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _089_ (
    .A(\next[4] ),
    .B(\next[3] ),
    .Y(_055_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand4_2 _090_ (
    .A(_052_),
    .B(_053_),
    .C(_054_),
    .D(_055_),
    .Y(_056_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _091_ (
    .A(\state[2] ),
    .X(_057_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _092_ (
    .A(_057_),
    .X(_058_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _093_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _094_ (
    .A(\state[0] ),
    .Y(_060_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _095_ (
    .A_N(_060_),
    .B(start),
    .Y(_061_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _096_ (
    .A(_059_),
    .B(_061_),
    .Y(_018_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _097_ (
    .A(\state[0] ),
    .X(_062_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _098_ (
    .A_N(start),
    .B(_062_),
    .Y(_063_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _099_ (
    .A_N(done),
    .B(_063_),
    .Y(_017_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _100_ (
    .A(out[0]),
    .Y(outn[0])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _101_ (
    .A(\next[0] ),
    .B(_057_),
    .Y(_064_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _102_ (
    .A_N(out[0]),
    .B(_064_),
    .Y(_065_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _103_ (
    .A(cmp),
    .Y(_066_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3_2 _104_ (
    .A(_066_),
    .B(\shift[0] ),
    .C(_058_),
    .Y(_067_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _105_ (
    .A(_060_),
    .X(_068_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3_2 _106_ (
    .A(_065_),
    .B(_067_),
    .C(_068_),
    .Y(_069_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _107_ (
    .A(_069_),
    .Y(_000_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _108_ (
    .A(out[1]),
    .Y(outn[1])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _109_ (
    .A(cmp),
    .X(_070_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _110_ (
    .A(_070_),
    .B(_064_),
    .Y(_071_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _111_ (
    .A(\next[1] ),
    .B(_057_),
    .Y(_072_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _112_ (
    .A_N(out[1]),
    .B(_072_),
    .Y(_073_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _113_ (
    .A_N(_071_),
    .B(_073_),
    .C(_068_),
    .Y(_074_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _114_ (
    .A(_074_),
    .Y(_001_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _115_ (
    .A(out[2]),
    .Y(outn[2])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _116_ (
    .A(_070_),
    .B(_072_),
    .Y(_075_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _117_ (
    .A(\state[2] ),
    .X(_076_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _118_ (
    .A(\next[2] ),
    .B(_076_),
    .Y(_077_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _119_ (
    .A_N(out[2]),
    .B(_077_),
    .Y(_078_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _120_ (
    .A_N(_075_),
    .B(_078_),
    .C(_068_),
    .Y(_079_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _121_ (
    .A(_079_),
    .Y(_002_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _122_ (
    .A(out[3]),
    .Y(outn[3])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _123_ (
    .A(_070_),
    .B(_077_),
    .Y(_080_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _124_ (
    .A(\next[3] ),
    .B(_076_),
    .Y(_081_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _125_ (
    .A_N(out[3]),
    .B(_081_),
    .Y(_082_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _126_ (
    .A_N(_080_),
    .B(_082_),
    .C(_068_),
    .Y(_083_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _127_ (
    .A(_083_),
    .Y(_003_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _128_ (
    .A(out[4]),
    .Y(outn[4])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _129_ (
    .A(_070_),
    .B(_081_),
    .Y(_084_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _130_ (
    .A(\next[4] ),
    .B(_076_),
    .Y(_022_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _131_ (
    .A_N(out[4]),
    .B(_022_),
    .Y(_023_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _132_ (
    .A_N(_084_),
    .B(_023_),
    .C(_060_),
    .Y(_024_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _133_ (
    .A(_024_),
    .Y(_004_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _134_ (
    .A(out[5]),
    .Y(outn[5])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _135_ (
    .A(_070_),
    .B(_022_),
    .Y(_025_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _136_ (
    .A(\next[5] ),
    .B(_076_),
    .Y(_026_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _137_ (
    .A_N(out[5]),
    .B(_026_),
    .Y(_027_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _138_ (
    .A_N(_025_),
    .B(_027_),
    .C(_068_),
    .Y(_028_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _139_ (
    .A(_028_),
    .Y(_005_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _140_ (
    .A(out[6]),
    .Y(outn[6])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _141_ (
    .A(cmp),
    .B(_026_),
    .Y(_029_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _142_ (
    .A(\next[6] ),
    .B(_057_),
    .Y(_030_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _143_ (
    .A_N(out[6]),
    .B(_030_),
    .Y(_031_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _144_ (
    .A_N(_029_),
    .B(_031_),
    .C(_060_),
    .Y(_032_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _145_ (
    .A(_032_),
    .Y(_006_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _146_ (
    .A(out[7]),
    .Y(outn[7])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _147_ (
    .A_N(_030_),
    .B(_066_),
    .Y(_033_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _148_ (
    .A_N(outn[7]),
    .B(_033_),
    .Y(_034_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _149_ (
    .A_N(_062_),
    .B(_034_),
    .Y(_007_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _150_ (
    .A(\state[0] ),
    .X(_035_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _151_ (
    .A(_058_),
    .B_N(\shift[0] ),
    .Y(_036_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _152_ (
    .A(_036_),
    .B_N(_064_),
    .Y(_037_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _153_ (
    .A(_035_),
    .B(_037_),
    .Y(_008_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _154_ (
    .A(_076_),
    .B_N(\next[0] ),
    .Y(_038_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _155_ (
    .A(_038_),
    .B_N(_072_),
    .Y(_039_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _156_ (
    .A(_062_),
    .B(_039_),
    .Y(_009_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _157_ (
    .A(_057_),
    .X(_040_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _158_ (
    .A(_040_),
    .B_N(\next[1] ),
    .Y(_041_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _159_ (
    .A(_041_),
    .B_N(_077_),
    .Y(_042_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _160_ (
    .A(_062_),
    .B(_042_),
    .Y(_010_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _161_ (
    .A(_040_),
    .B_N(\next[2] ),
    .Y(_043_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _162_ (
    .A(_043_),
    .B_N(_081_),
    .Y(_044_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _163_ (
    .A(_035_),
    .B(_044_),
    .Y(_011_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _164_ (
    .A(_040_),
    .B_N(\next[3] ),
    .Y(_045_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _165_ (
    .A(_045_),
    .B_N(_022_),
    .Y(_046_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _166_ (
    .A(_035_),
    .B(_046_),
    .Y(_012_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _167_ (
    .A(_040_),
    .B_N(\next[4] ),
    .Y(_047_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _168_ (
    .A(_047_),
    .B_N(_026_),
    .Y(_048_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _169_ (
    .A(_035_),
    .B(_048_),
    .Y(_013_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _170_ (
    .A(_040_),
    .B_N(\next[5] ),
    .Y(_049_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _171_ (
    .A(_049_),
    .B_N(_030_),
    .Y(_050_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _172_ (
    .A(_035_),
    .B(_050_),
    .Y(_014_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _173_ (
    .A_N(_058_),
    .B(\next[6] ),
    .Y(_051_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _174_ (
    .A_N(_062_),
    .B(_051_),
    .Y(_015_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _175_ (
    .A(clk),
    .Y(clkn)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _176_ (
    .A(_056_),
    .B_N(_058_),
    .Y(_016_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _177_ (
    .A(rst),
    .Y(_019_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _178_ (
    .A(rst),
    .Y(_020_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _179_ (
    .CLK(clk),
    .D(_000_),
    .Q(out[0])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _180_ (
    .CLK(clk),
    .D(_001_),
    .Q(out[1])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _181_ (
    .CLK(clk),
    .D(_002_),
    .Q(out[2])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _182_ (
    .CLK(clk),
    .D(_003_),
    .Q(out[3])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _183_ (
    .CLK(clk),
    .D(_004_),
    .Q(out[4])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _184_ (
    .CLK(clk),
    .D(_005_),
    .Q(out[5])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _185_ (
    .CLK(clk),
    .D(_006_),
    .Q(out[6])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _186_ (
    .CLK(clk),
    .D(_007_),
    .Q(out[7])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _187_ (
    .CLK(clk),
    .D(_008_),
    .Q(\shift[0] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _188_ (
    .CLK(clk),
    .D(_009_),
    .Q(\next[0] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _189_ (
    .CLK(clk),
    .D(_010_),
    .Q(\next[1] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _190_ (
    .CLK(clk),
    .D(_011_),
    .Q(\next[2] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _191_ (
    .CLK(clk),
    .D(_012_),
    .Q(\next[3] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _192_ (
    .CLK(clk),
    .D(_013_),
    .Q(\next[4] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _193_ (
    .CLK(clk),
    .D(_014_),
    .Q(\next[5] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _194_ (
    .CLK(clk),
    .D(_015_),
    .Q(\next[6] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfstp_4 _195_ (
    .CLK(clk),
    .D(_017_),
    .Q(\state[0] ),
    .SET_B(_019_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfrtp_4 _196_ (
    .CLK(clk),
    .D(_016_),
    .Q(done),
    .RESET_B(_020_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfrtp_4 _197_ (
    .CLK(clk),
    .D(_018_),
    .Q(\state[2] ),
    .RESET_B(_021_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
endmodule
