/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

module SAR(clk, rstn, start, cmp, out, outn, done, clkn, VGND, VNB, VPB, VPWR);
  input  VPWR;
  input  VGND;
  input  VPB ;
  input  VNB ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  input clk;
  output clkn;
  input cmp;
  output done;
  wire \next[0] ;
  wire \next[1] ;
  wire \next[2] ;
  wire \next[3] ;
  wire \next[4] ;
  wire \next[5] ;
  wire \next[6] ;
  output [7:0] out;
  output [7:0] outn;
  input rstn;
  wire \shift[0] ;
  input start;
  wire \state[0] ;
  wire \state[2] ;
  sky130_fd_sc_hd__nor2b_2 _082_ (
    .A(\next[0] ),
    .B_N(\shift[0] ),
    .Y(_046_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _083_ (
    .A(\next[2] ),
    .B(\next[1] ),
    .Y(_047_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _084_ (
    .A(\next[6] ),
    .B(\next[5] ),
    .Y(_048_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _085_ (
    .A(\next[4] ),
    .B(\next[3] ),
    .Y(_049_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand4_2 _086_ (
    .A(_046_),
    .B(_047_),
    .C(_048_),
    .D(_049_),
    .Y(_050_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _087_ (
    .A(\state[2] ),
    .X(_051_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _088_ (
    .A(_051_),
    .X(_052_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _089_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _090_ (
    .A(\state[0] ),
    .Y(_054_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _091_ (
    .A_N(_054_),
    .B(start),
    .Y(_055_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _092_ (
    .A(_053_),
    .B(_055_),
    .Y(_018_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _093_ (
    .A(\state[0] ),
    .X(_056_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _094_ (
    .A_N(start),
    .B(_056_),
    .Y(_057_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _095_ (
    .A_N(done),
    .B(_057_),
    .Y(_017_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _096_ (
    .A(out[0]),
    .Y(outn[0])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _097_ (
    .A(\next[0] ),
    .B(_051_),
    .Y(_058_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _098_ (
    .A_N(out[0]),
    .B(_058_),
    .Y(_059_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _099_ (
    .A(cmp),
    .Y(_060_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3_2 _100_ (
    .A(_060_),
    .B(\shift[0] ),
    .C(_052_),
    .Y(_061_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _101_ (
    .A(_054_),
    .X(_062_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3_2 _102_ (
    .A(_059_),
    .B(_061_),
    .C(_062_),
    .Y(_063_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _103_ (
    .A(_063_),
    .Y(_000_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _104_ (
    .A(out[1]),
    .Y(outn[1])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _105_ (
    .A(cmp),
    .X(_064_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _106_ (
    .A(_064_),
    .B(_058_),
    .Y(_065_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _107_ (
    .A(\next[1] ),
    .B(_051_),
    .Y(_066_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _108_ (
    .A_N(out[1]),
    .B(_066_),
    .Y(_067_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _109_ (
    .A_N(_065_),
    .B(_067_),
    .C(_062_),
    .Y(_068_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _110_ (
    .A(_068_),
    .Y(_001_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _111_ (
    .A(out[2]),
    .Y(outn[2])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _112_ (
    .A(_064_),
    .B(_066_),
    .Y(_069_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _113_ (
    .A(\state[2] ),
    .X(_070_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _114_ (
    .A(\next[2] ),
    .B(_070_),
    .Y(_071_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _115_ (
    .A_N(out[2]),
    .B(_071_),
    .Y(_072_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _116_ (
    .A_N(_069_),
    .B(_072_),
    .C(_062_),
    .Y(_073_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _117_ (
    .A(_073_),
    .Y(_002_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _118_ (
    .A(out[3]),
    .Y(outn[3])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _119_ (
    .A(_064_),
    .B(_071_),
    .Y(_074_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _120_ (
    .A(\next[3] ),
    .B(_070_),
    .Y(_075_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _121_ (
    .A_N(out[3]),
    .B(_075_),
    .Y(_076_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _122_ (
    .A_N(_074_),
    .B(_076_),
    .C(_062_),
    .Y(_077_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _123_ (
    .A(_077_),
    .Y(_003_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _124_ (
    .A(out[4]),
    .Y(outn[4])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _125_ (
    .A(_064_),
    .B(_075_),
    .Y(_078_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _126_ (
    .A(\next[4] ),
    .B(_070_),
    .Y(_079_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _127_ (
    .A_N(out[4]),
    .B(_079_),
    .Y(_080_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _128_ (
    .A_N(_078_),
    .B(_080_),
    .C(_054_),
    .Y(_081_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _129_ (
    .A(_081_),
    .Y(_004_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _130_ (
    .A(out[5]),
    .Y(outn[5])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _131_ (
    .A(_064_),
    .B(_079_),
    .Y(_019_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _132_ (
    .A(\next[5] ),
    .B(_070_),
    .Y(_020_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _133_ (
    .A_N(out[5]),
    .B(_020_),
    .Y(_021_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _134_ (
    .A_N(_019_),
    .B(_021_),
    .C(_062_),
    .Y(_022_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _135_ (
    .A(_022_),
    .Y(_005_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _136_ (
    .A(out[6]),
    .Y(outn[6])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _137_ (
    .A(cmp),
    .B(_020_),
    .Y(_023_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2_4 _138_ (
    .A(\next[6] ),
    .B(_051_),
    .Y(_024_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _139_ (
    .A_N(out[6]),
    .B(_024_),
    .Y(_025_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand3b_2 _140_ (
    .A_N(_023_),
    .B(_025_),
    .C(_054_),
    .Y(_026_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _141_ (
    .A(_026_),
    .Y(_006_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _142_ (
    .A(out[7]),
    .Y(outn[7])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _143_ (
    .A_N(_024_),
    .B(_060_),
    .Y(_027_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _144_ (
    .A_N(outn[7]),
    .B(_027_),
    .Y(_028_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _145_ (
    .A_N(_056_),
    .B(_028_),
    .Y(_007_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _146_ (
    .A(\state[0] ),
    .X(_029_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _147_ (
    .A(_052_),
    .B_N(\shift[0] ),
    .Y(_030_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _148_ (
    .A(_030_),
    .B_N(_058_),
    .Y(_031_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _149_ (
    .A(_029_),
    .B(_031_),
    .Y(_008_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _150_ (
    .A(_070_),
    .B_N(\next[0] ),
    .Y(_032_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _151_ (
    .A(_032_),
    .B_N(_066_),
    .Y(_033_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _152_ (
    .A(_056_),
    .B(_033_),
    .Y(_009_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__buf_2 _153_ (
    .A(_051_),
    .X(_034_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _154_ (
    .A(_034_),
    .B_N(\next[1] ),
    .Y(_035_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _155_ (
    .A(_035_),
    .B_N(_071_),
    .Y(_036_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _156_ (
    .A(_056_),
    .B(_036_),
    .Y(_010_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _157_ (
    .A(_034_),
    .B_N(\next[2] ),
    .Y(_037_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _158_ (
    .A(_037_),
    .B_N(_075_),
    .Y(_038_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _159_ (
    .A(_029_),
    .B(_038_),
    .Y(_011_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _160_ (
    .A(_034_),
    .B_N(\next[3] ),
    .Y(_039_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _161_ (
    .A(_039_),
    .B_N(_079_),
    .Y(_040_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _162_ (
    .A(_029_),
    .B(_040_),
    .Y(_012_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _163_ (
    .A(_034_),
    .B_N(\next[4] ),
    .Y(_041_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _164_ (
    .A(_041_),
    .B_N(_020_),
    .Y(_042_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _165_ (
    .A(_029_),
    .B(_042_),
    .Y(_013_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _166_ (
    .A(_034_),
    .B_N(\next[5] ),
    .Y(_043_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _167_ (
    .A(_043_),
    .B_N(_024_),
    .Y(_044_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2_2 _168_ (
    .A(_029_),
    .B(_044_),
    .Y(_014_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _169_ (
    .A_N(_052_),
    .B(\next[6] ),
    .Y(_045_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nand2b_2 _170_ (
    .A_N(_056_),
    .B(_045_),
    .Y(_015_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__inv_2 _171_ (
    .A(clk),
    .Y(clkn)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__nor2b_2 _172_ (
    .A(_050_),
    .B_N(_052_),
    .Y(_016_)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _173_ (
    .CLK(clk),
    .D(_000_),
    .Q(out[0])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _174_ (
    .CLK(clk),
    .D(_001_),
    .Q(out[1])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _175_ (
    .CLK(clk),
    .D(_002_),
    .Q(out[2])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _176_ (
    .CLK(clk),
    .D(_003_),
    .Q(out[3])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _177_ (
    .CLK(clk),
    .D(_004_),
    .Q(out[4])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _178_ (
    .CLK(clk),
    .D(_005_),
    .Q(out[5])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _179_ (
    .CLK(clk),
    .D(_006_),
    .Q(out[6])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _180_ (
    .CLK(clk),
    .D(_007_),
    .Q(out[7])
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _181_ (
    .CLK(clk),
    .D(_008_),
    .Q(\shift[0] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _182_ (
    .CLK(clk),
    .D(_009_),
    .Q(\next[0] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _183_ (
    .CLK(clk),
    .D(_010_),
    .Q(\next[1] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _184_ (
    .CLK(clk),
    .D(_011_),
    .Q(\next[2] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _185_ (
    .CLK(clk),
    .D(_012_),
    .Q(\next[3] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _186_ (
    .CLK(clk),
    .D(_013_),
    .Q(\next[4] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _187_ (
    .CLK(clk),
    .D(_014_),
    .Q(\next[5] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfxtp_4 _188_ (
    .CLK(clk),
    .D(_015_),
    .Q(\next[6] )
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfstp_4 _189_ (
    .CLK(clk),
    .D(_017_),
    .Q(\state[0] ),
    .SET_B(rstn)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfrtp_4 _190_ (
    .CLK(clk),
    .D(_016_),
    .Q(done),
    .RESET_B(rstn)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
  sky130_fd_sc_hd__dfrtp_4 _191_ (
    .CLK(clk),
    .D(_018_),
    .Q(\state[2] ),
    .RESET_B(rstn)
    , .VGND(VGND), .VNB(VNB), .VPB(VPB), .VPWR(VPWR)
  );
endmodule
